--- #YAML:1.0
name:                Sub-Contract
version:             0.10
abstract:            Pragmatic contract programming for Perl
license:             ~
author:              
    - Erwan Lemonnier <erwan@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    accessors:                     0.02
    Sub::Name:                     0.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
