--- #YAML:1.0
name:                Sub-Contract
version:             0.06
abstract:            Pragmatic contract programming for Perl
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    accessors:                     0.02
    Cache:                         2
    Sub::Name:                     0.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Erwan Lemonnier <erwan@cpan.org>
