# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sub-Contract
version:      0.07
version_from: lib/Sub/Contract.pm
installdirs:  site
requires:
    accessors:                     0.02
    Cache:                         2
    Sub::Name:                     0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
